kaiwalyakoparkar/Data-Structures-And-Algorithm-Interview-Kit

.github/pull_request_template.md
=> Updated the pull request template

README.md
=> doc: Updated the current topic

ProblemSets/Array/AlternateNegativeAndPositiveNumbers/Question and Logic.md
#15
Renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautifull.
=> Fix #15 Renamed and formatted the 'Question and Logic.txt file'

ProblemSets/Array/CommonElementInThreeSortedArrays/Question and Logic.md
#15
On `CommonElementInThreeSortedArrays` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautifull.
=> Fix #15 of CommonElementInThreeSortedArrays Problem

README.md
=> doc: credits added

ProblemSets/Array/MinimiseTheMaximumDifferenceBtwHeights/Question and Logic.md
#15
On `MinimiseTheMaximumDifferenceBtwHeights` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 of MinimiseTheMaximumDifferenceBtwHeights Problem

ProblemSets/Array/TrappingWaterProblem/Question and Logic.md
#15
On `TrappingWaterProblem` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 of TrappingWaterProblem Problem

ProblemSets/Matrix/SpiralTraversalOfMatrix/Question and Logic.md
#15
On `SpiralTraversalOfMatrix` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 of SpiralTraversalOfMatrix Problem

ProblemSets/Matrix/SearchElementInMatrix/Question and Logic.md
#15
On `SearchElementInMatrix` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 SearchElementInMatrix Problem

ProblemSets/Matrix/RowWithMaximumOnes/Question and Logic.md
#15
On `RowWithMaximumOnes` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 of RowWithMaximumOnes Problem

ProblemSets/Matrix/RotateTheMatrixBy90Degree/Question and Logic.md
#15
On `RotateTheMatrixBy90Degree` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 RotateTheMatrixBy90Degree Problem

ProblemSets/Matrix/MaximumSizeRectangle/Question and Logic.md
#15
On `MaximumSizeRectangle` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 of MaximumSizeRectangle Problem

ProblemSets/Matrix/CommonElementsInAllRows/Question and Logic.md
#15
On `CommonElementsInAllRows` folder renamed the `Question and Logic.txt` file to `Question and Logic.md` and formatted it to look beautiful.
=> Fix #15 of CommonElementsInAllRows Problem

ProblemSets/Strings/CountPalindromicSubsequences/Question and Logic.md
=> Documentation added

ProblemSets/Strings/BoyerMooreAlgorithm/Solution.java
=> Started boyer moore algorithm

ProblemSets/Binary Trees/DiameterOfBinaryTree/Question and Logic.md
=> :memo: Documentation added for diameter of the binary tree

.github/workflows/greetings.yml
=> Add: :rocket: Workflows added for greeting the people contributing

ProblemSets/LinkedList/DetectALoop/Logic.md
=> Add: :heavy_plus_sign: Detected a loop in the linked list

ProblemSets/Greedy Technique/JobSequencing/Question and Logic.md
=> Add: :heavy_plus_sign: Test cases added

ProblemSets/Heap/ImplementHeap/Solution.java
=> feat: :memo: Tree created for heap

ProblemSets/LinkedList/DeleteALoop/Logic.md, ProblemSets/LinkedList/FindStartingPointOfTheLoop/Logic.md
=> Delete the loop and Starting of the loop problem solved

.github/FUNDING.yml
- Fix BuyMeACoffee funding link
I don't think this applies here.
=> Fix BuyMeACoffee funding link
